// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef _UI_COMP_TEMP_H
#define _UI_COMP_TEMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT temp
#define UI_COMP_TEMP_TEMP 0
#define _UI_COMP_TEMP_NUM 1
lv_obj_t * ui_temp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
