// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

// COMPONENT temp

lv_obj_t * ui_temp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_temp;
    cui_temp = lv_label_create(comp_parent);
    lv_obj_set_width(cui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_temp, -1);
    lv_obj_set_y(cui_temp, -29);
    lv_obj_set_align(cui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(cui_temp, "28°C");
    lv_obj_set_style_text_color(cui_temp, lv_color_hex(0xF6EDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_temp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TEMP_NUM);
    children[UI_COMP_TEMP_TEMP] = cui_temp;
    lv_obj_add_event_cb(cui_temp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_temp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_temp_create_hook(cui_temp);
    return cui_temp;
}

