// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * uic_time;
lv_obj_t * uic_connection;
lv_obj_t * ui_connection = NULL;
lv_obj_t * ui_mid1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_authenticate = NULL;
lv_obj_t * ui_verify = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_handshake = NULL;
lv_obj_t * ui_timeout = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_header1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_footer1 = NULL;
lv_obj_t * ui_sync1 = NULL;
lv_obj_t * ui_systemReady1 = NULL;
// event funtions
void ui_event_connection(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ready2charge, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_ready2charge_screen_init);
    }
}

// build funtions

void ui_connection_screen_init(void)
{
    ui_connection = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_connection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mid1 = lv_obj_create(ui_connection);
    lv_obj_remove_style_all(ui_mid1);
    lv_obj_set_width(ui_mid1, 305);
    lv_obj_set_height(ui_mid1, 166);
    lv_obj_set_x(ui_mid1, 0);
    lv_obj_set_y(ui_mid1, 6);
    lv_obj_set_align(ui_mid1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mid1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mid1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mid1, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mid1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mid1, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mid1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_mid1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_mid1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_mid1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 61);
    lv_obj_set_height(ui_Container1, 61);
    lv_obj_set_x(ui_Container1, 5);
    lv_obj_set_y(ui_Container1, -24);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Container1);
    lv_image_set_src(ui_Image5, &ui_img_971831803);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 0);
    lv_obj_set_y(ui_Image5, 2);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_authenticate = lv_label_create(ui_mid1);
    lv_obj_set_width(ui_authenticate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_authenticate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_authenticate, 4);
    lv_obj_set_y(ui_authenticate, 33);
    lv_obj_set_align(ui_authenticate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_authenticate, "AUTHENTICATING");
    lv_obj_set_style_text_color(ui_authenticate, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_authenticate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_authenticate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_verify = lv_label_create(ui_mid1);
    lv_obj_set_width(ui_verify, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_verify, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_verify, 6);
    lv_obj_set_y(ui_verify, 50);
    lv_obj_set_align(ui_verify, LV_ALIGN_CENTER);
    lv_label_set_text(ui_verify, "Verifying account...");
    lv_obj_set_style_text_color(ui_verify, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_verify, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_verify, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_mid1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 296);
    lv_obj_set_height(ui_Bar1, 4);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 80);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x20555C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_handshake = lv_label_create(ui_mid1);
    lv_obj_set_width(ui_handshake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_handshake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_handshake, -92);
    lv_obj_set_y(ui_handshake, 70);
    lv_obj_set_align(ui_handshake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_handshake, "HANDSHAKE STATUS");
    lv_obj_set_style_text_color(ui_handshake, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_handshake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_handshake, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeout = lv_label_create(ui_mid1);
    lv_obj_set_width(ui_timeout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeout, 91);
    lv_obj_set_y(ui_timeout, 69);
    lv_obj_set_align(ui_timeout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeout, "Timeout in");
    lv_obj_set_style_text_color(ui_timeout, lv_color_hex(0x14E0D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeout, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_connection);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 132);
    lv_obj_set_y(ui_time, 75);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "06s");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x40B6AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_connection);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 93);
    lv_obj_set_height(ui_Spinner1, 94);
    lv_obj_set_x(ui_Spinner1, 6);
    lv_obj_set_y(ui_Spinner1, -17);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x233C3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x29B4B7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_header1 = lv_obj_create(ui_connection);
    lv_obj_remove_style_all(ui_header1);
    lv_obj_set_width(ui_header1, 323);
    lv_obj_set_height(ui_header1, 27);
    lv_obj_set_x(ui_header1, -1);
    lv_obj_set_y(ui_header1, -103);
    lv_obj_set_align(ui_header1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header1, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_header1);
    lv_image_set_src(ui_Image1, &ui_img_1149014773);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -138);
    lv_obj_set_y(ui_Image1, -2);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 80);

    ui_Label1 = lv_label_create(ui_header1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -82);
    lv_obj_set_y(ui_Label1, -2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "MOMENTUM");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_header1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 75);
    lv_obj_set_y(ui_Label2, -2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CONNECTING");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_header1);
    lv_image_set_src(ui_Image4, &ui_img_493105991);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 135);
    lv_obj_set_y(ui_Image4, -3);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 120);

    ui_footer1 = lv_obj_create(ui_connection);
    lv_obj_remove_style_all(ui_footer1);
    lv_obj_set_width(ui_footer1, 313);
    lv_obj_set_height(ui_footer1, 17);
    lv_obj_set_x(ui_footer1, -1);
    lv_obj_set_y(ui_footer1, 107);
    lv_obj_set_align(ui_footer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer1, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync1 = lv_label_create(ui_footer1);
    lv_obj_set_width(ui_sync1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync1, 117);
    lv_obj_set_y(ui_sync1, 0);
    lv_obj_set_align(ui_sync1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync1, "SYSTEM READY");
    lv_obj_set_style_text_color(ui_sync1, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady1 = lv_label_create(ui_footer1);
    lv_obj_set_width(ui_systemReady1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady1, -72);
    lv_obj_set_y(ui_systemReady1, 0);
    lv_obj_set_align(ui_systemReady1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady1, "SYSTEM IDENTITY: EVCS-NG-001");
    lv_obj_set_style_text_color(ui_systemReady1, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_connection, ui_event_connection, LV_EVENT_ALL, NULL);
    uic_connection = ui_connection;
    uic_time = ui_time;

}

void ui_connection_screen_destroy(void)
{
    if(ui_connection) lv_obj_del(ui_connection);

    // NULL screen variables
    uic_connection = NULL;
    ui_connection = NULL;
    ui_mid1 = NULL;
    ui_Container1 = NULL;
    ui_Image5 = NULL;
    ui_authenticate = NULL;
    ui_verify = NULL;
    ui_Bar1 = NULL;
    ui_handshake = NULL;
    ui_timeout = NULL;
    uic_time = NULL;
    ui_time = NULL;
    ui_Spinner1 = NULL;
    ui_header1 = NULL;
    ui_Image1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Image4 = NULL;
    ui_footer1 = NULL;
    ui_sync1 = NULL;
    ui_systemReady1 = NULL;

}
