// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_CONNECTION_H
#define UI_CONNECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_connection
extern void ui_connection_screen_init(void);
extern void ui_connection_screen_destroy(void);
extern void ui_event_connection(lv_event_t * e);
extern lv_obj_t * ui_connection;
extern lv_obj_t * ui_mid1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_authenticate;
extern lv_obj_t * ui_verify;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_handshake;
extern lv_obj_t * ui_timeout;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_header1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_footer1;
extern lv_obj_t * ui_sync1;
extern lv_obj_t * ui_systemReady1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_connection;
extern lv_obj_t * uic_time;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

