// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * ui_fault = NULL;
lv_obj_t * ui_header3 = NULL;
lv_obj_t * ui_logo1 = NULL;
lv_obj_t * ui_momentum1 = NULL;
lv_obj_t * ui_wifi1 = NULL;
lv_obj_t * ui_footer3 = NULL;
lv_obj_t * ui_sync3 = NULL;
lv_obj_t * ui_systemReady3 = NULL;
lv_obj_t * ui_faultstatus = NULL;
lv_obj_t * ui_done1 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_sessioncompletelabel1 = NULL;
lv_obj_t * ui_ACKNOLEDGEBUTTON = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_faultstatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        blink_Animation(ui_faultstatus, 500);
    }
}

void ui_event_ACKNOLEDGEBUTTON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_stoppedsreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_stoppedsreen_screen_init);
    }
}

// build funtions

void ui_fault_screen_init(void)
{
    ui_fault = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_fault, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header3 = lv_obj_create(ui_fault);
    lv_obj_remove_style_all(ui_header3);
    lv_obj_set_width(ui_header3, 323);
    lv_obj_set_height(ui_header3, 27);
    lv_obj_set_x(ui_header3, -1);
    lv_obj_set_y(ui_header3, -103);
    lv_obj_set_align(ui_header3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header3, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo1 = lv_image_create(ui_header3);
    lv_image_set_src(ui_logo1, &ui_img_1783177842);
    lv_obj_set_width(ui_logo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo1, -138);
    lv_obj_set_y(ui_logo1, -2);
    lv_obj_set_align(ui_logo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo1, 80);

    ui_momentum1 = lv_label_create(ui_header3);
    lv_obj_set_width(ui_momentum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum1, -100);
    lv_obj_set_y(ui_momentum1, -2);
    lv_obj_set_align(ui_momentum1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum1, "FAULT");
    lv_obj_set_style_text_color(ui_momentum1, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi1 = lv_image_create(ui_header3);
    lv_image_set_src(ui_wifi1, &ui_img_493105991);
    lv_obj_set_width(ui_wifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi1, 135);
    lv_obj_set_y(ui_wifi1, -3);
    lv_obj_set_align(ui_wifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi1, 120);

    ui_footer3 = lv_obj_create(ui_fault);
    lv_obj_remove_style_all(ui_footer3);
    lv_obj_set_width(ui_footer3, 313);
    lv_obj_set_height(ui_footer3, 17);
    lv_obj_set_x(ui_footer3, -1);
    lv_obj_set_y(ui_footer3, 107);
    lv_obj_set_align(ui_footer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer3, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync3 = lv_label_create(ui_footer3);
    lv_obj_set_width(ui_sync3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync3, 130);
    lv_obj_set_y(ui_sync3, 0);
    lv_obj_set_align(ui_sync3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync3, "Critical");
    lv_obj_set_style_text_color(ui_sync3, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady3 = lv_label_create(ui_footer3);
    lv_obj_set_width(ui_systemReady3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady3, -107);
    lv_obj_set_y(ui_systemReady3, 1);
    lv_obj_set_align(ui_systemReady3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady3, "System Ready");
    lv_obj_set_style_text_color(ui_systemReady3, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_faultstatus = lv_image_create(ui_footer3);
    lv_image_set_src(ui_faultstatus, &ui_img_1554972560);
    lv_obj_set_width(ui_faultstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_faultstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_faultstatus, 103);
    lv_obj_set_y(ui_faultstatus, 0);
    lv_obj_set_align(ui_faultstatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_faultstatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_faultstatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_faultstatus, 120);

    ui_done1 = lv_obj_create(ui_fault);
    lv_obj_remove_style_all(ui_done1);
    lv_obj_set_width(ui_done1, 58);
    lv_obj_set_height(ui_done1, 56);
    lv_obj_set_x(ui_done1, 1);
    lv_obj_set_y(ui_done1, -49);
    lv_obj_set_align(ui_done1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_done1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_done1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_done1, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_done1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_done1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_done1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_image_create(ui_done1);
    lv_image_set_src(ui_Image13, &ui_img_104383894);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 0);
    lv_obj_set_y(ui_Image13, -3);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_fault);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 290);
    lv_obj_set_height(ui_Container10, 89);
    lv_obj_set_x(ui_Container10, -1);
    lv_obj_set_y(ui_Container10, 33);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container10, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sessioncompletelabel1 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_sessioncompletelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sessioncompletelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sessioncompletelabel1, 1);
    lv_obj_set_y(ui_sessioncompletelabel1, -25);
    lv_obj_set_align(ui_sessioncompletelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sessioncompletelabel1, "CHARGING FAULT");
    lv_obj_set_style_text_color(ui_sessioncompletelabel1, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sessioncompletelabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sessioncompletelabel1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACKNOLEDGEBUTTON = lv_button_create(ui_fault);
    lv_obj_set_width(ui_ACKNOLEDGEBUTTON, 206);
    lv_obj_set_height(ui_ACKNOLEDGEBUTTON, 33);
    lv_obj_set_x(ui_ACKNOLEDGEBUTTON, 3);
    lv_obj_set_y(ui_ACKNOLEDGEBUTTON, 48);
    lv_obj_set_align(ui_ACKNOLEDGEBUTTON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACKNOLEDGEBUTTON, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ACKNOLEDGEBUTTON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ACKNOLEDGEBUTTON, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ACKNOLEDGEBUTTON, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACKNOLEDGEBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ACKNOLEDGEBUTTON, lv_color_hex(0xEEC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ACKNOLEDGEBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ACKNOLEDGEBUTTON, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ACKNOLEDGEBUTTON, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ACKNOLEDGEBUTTON, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ACKNOLEDGEBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_fault);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 4);
    lv_obj_set_y(ui_Label12, 48);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "ACKNOWLEDGE");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_faultstatus, ui_event_faultstatus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ACKNOLEDGEBUTTON, ui_event_ACKNOLEDGEBUTTON, LV_EVENT_ALL, NULL);

}

void ui_fault_screen_destroy(void)
{
    if(ui_fault) lv_obj_del(ui_fault);

    // NULL screen variables
    ui_fault = NULL;
    ui_header3 = NULL;
    ui_logo1 = NULL;
    ui_momentum1 = NULL;
    ui_wifi1 = NULL;
    ui_footer3 = NULL;
    ui_sync3 = NULL;
    ui_systemReady3 = NULL;
    ui_faultstatus = NULL;
    ui_done1 = NULL;
    ui_Image13 = NULL;
    ui_Container10 = NULL;
    ui_sessioncompletelabel1 = NULL;
    ui_ACKNOLEDGEBUTTON = NULL;
    ui_Label12 = NULL;

}
