// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_FAULT_H
#define UI_FAULT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_fault
extern void ui_fault_screen_init(void);
extern void ui_fault_screen_destroy(void);
extern lv_obj_t * ui_fault;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_logo1;
extern lv_obj_t * ui_momentum1;
extern lv_obj_t * ui_wifi1;
extern lv_obj_t * ui_footer3;
extern lv_obj_t * ui_sync3;
extern lv_obj_t * ui_systemReady3;
extern void ui_event_faultstatus(lv_event_t * e);
extern lv_obj_t * ui_faultstatus;
extern lv_obj_t * ui_done1;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_sessioncompletelabel1;
extern void ui_event_ACKNOLEDGEBUTTON(lv_event_t * e);
extern lv_obj_t * ui_ACKNOLEDGEBUTTON;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

