// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * ui_powerandenergy = NULL;
lv_obj_t * ui_header5 = NULL;
lv_obj_t * ui_logo3 = NULL;
lv_obj_t * ui_momentum3 = NULL;
lv_obj_t * ui_status3 = NULL;
lv_obj_t * ui_wifi3 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_footer5 = NULL;
lv_obj_t * ui_sync5 = NULL;
lv_obj_t * ui_systemReady5 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_energy = NULL;
lv_obj_t * ui_energydeliver = NULL;
lv_obj_t * ui_energyvalue = NULL;
lv_obj_t * ui_kwh = NULL;
lv_obj_t * ui_power = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_powervalue = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_powerlabel = NULL;
lv_obj_t * ui_Bar3 = NULL;
lv_obj_t * ui_soc = NULL;
lv_obj_t * ui_stopcharging = NULL;
// event funtions
void ui_event_powerandenergy(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_sessioncomplete, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_sessioncomplete_screen_init);
    }
}

// build funtions

void ui_powerandenergy_screen_init(void)
{
    ui_powerandenergy = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_powerandenergy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header5 = lv_obj_create(ui_powerandenergy);
    lv_obj_remove_style_all(ui_header5);
    lv_obj_set_width(ui_header5, 323);
    lv_obj_set_height(ui_header5, 27);
    lv_obj_set_x(ui_header5, -1);
    lv_obj_set_y(ui_header5, -103);
    lv_obj_set_align(ui_header5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header5, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo3 = lv_image_create(ui_header5);
    lv_image_set_src(ui_logo3, &ui_img_1149014773);
    lv_obj_set_width(ui_logo3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo3, -138);
    lv_obj_set_y(ui_logo3, -2);
    lv_obj_set_align(ui_logo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo3, 80);

    ui_momentum3 = lv_label_create(ui_header5);
    lv_obj_set_width(ui_momentum3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum3, -82);
    lv_obj_set_y(ui_momentum3, -2);
    lv_obj_set_align(ui_momentum3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum3, "MOMENTUM");
    lv_obj_set_style_text_color(ui_momentum3, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status3 = lv_label_create(ui_header5);
    lv_obj_set_width(ui_status3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status3, 83);
    lv_obj_set_y(ui_status3, -2);
    lv_obj_set_align(ui_status3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status3, "CHARGING");
    lv_obj_set_style_text_color(ui_status3, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_status3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi3 = lv_image_create(ui_header5);
    lv_image_set_src(ui_wifi3, &ui_img_493105991);
    lv_obj_set_width(ui_wifi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi3, 135);
    lv_obj_set_y(ui_wifi3, -3);
    lv_obj_set_align(ui_wifi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi3, 120);

    ui_Image9 = lv_image_create(ui_header5);
    lv_image_set_src(ui_Image9, &ui_img_98824070);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 38);
    lv_obj_set_y(ui_Image9, -2);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image9, 100);

    ui_footer5 = lv_obj_create(ui_powerandenergy);
    lv_obj_remove_style_all(ui_footer5);
    lv_obj_set_width(ui_footer5, 313);
    lv_obj_set_height(ui_footer5, 17);
    lv_obj_set_x(ui_footer5, -1);
    lv_obj_set_y(ui_footer5, 107);
    lv_obj_set_align(ui_footer5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer5, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync5 = lv_label_create(ui_footer5);
    lv_obj_set_width(ui_sync5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync5, 117);
    lv_obj_set_y(ui_sync5, 0);
    lv_obj_set_align(ui_sync5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync5, "CCS TYPE 2");
    lv_obj_set_style_text_color(ui_sync5, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady5 = lv_label_create(ui_footer5);
    lv_obj_set_width(ui_systemReady5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady5, -113);
    lv_obj_set_y(ui_systemReady5, -1);
    lv_obj_set_align(ui_systemReady5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady5, "SYSTEM READY");
    lv_obj_set_style_text_color(ui_systemReady5, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_image_create(ui_footer5);
    lv_image_set_src(ui_Image11, &ui_img_480528337);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 79);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image11, 70);

    ui_energy = lv_obj_create(ui_powerandenergy);
    lv_obj_remove_style_all(ui_energy);
    lv_obj_set_width(ui_energy, 176);
    lv_obj_set_height(ui_energy, 135);
    lv_obj_set_x(ui_energy, -61);
    lv_obj_set_y(ui_energy, -1);
    lv_obj_set_align(ui_energy, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_energy, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_energy, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_energy, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_energy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_energy, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_energy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_energy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_energy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energydeliver = lv_label_create(ui_energy);
    lv_obj_set_width(ui_energydeliver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energydeliver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_energydeliver, -16);
    lv_obj_set_y(ui_energydeliver, -16);
    lv_obj_set_align(ui_energydeliver, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energydeliver, "ENERGY DELIVERED");
    lv_obj_set_style_text_color(ui_energydeliver, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_energydeliver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_energydeliver, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyvalue = lv_label_create(ui_energy);
    lv_obj_set_width(ui_energyvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_energyvalue, -30);
    lv_obj_set_y(ui_energyvalue, 14);
    lv_obj_set_align(ui_energyvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyvalue, "12.45");
    lv_obj_set_style_text_font(ui_energyvalue, &ui_font_supp22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kwh = lv_label_create(ui_energy);
    lv_obj_set_width(ui_kwh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kwh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kwh, 43);
    lv_obj_set_y(ui_kwh, 17);
    lv_obj_set_align(ui_kwh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kwh, "KWh");
    lv_obj_set_style_text_color(ui_kwh, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kwh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kwh, &ui_font_supp20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power = lv_obj_create(ui_powerandenergy);
    lv_obj_remove_style_all(ui_power);
    lv_obj_set_width(ui_power, 98);
    lv_obj_set_height(ui_power, 135);
    lv_obj_set_x(ui_power, 93);
    lv_obj_set_y(ui_power, 0);
    lv_obj_set_align(ui_power, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_power, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_power, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_power, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_power, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_power);
    lv_obj_set_width(ui_Arc1, 148);
    lv_obj_set_height(ui_Arc1, 88);
    lv_obj_set_x(ui_Arc1, 32);
    lv_obj_set_y(ui_Arc1, 12);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 30);
    lv_arc_set_value(ui_Arc1, 22);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Arc1, 90);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x35494C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x3FC5D9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Arc1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_powervalue = lv_label_create(ui_power);
    lv_obj_set_width(ui_powervalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powervalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powervalue, 2);
    lv_obj_set_y(ui_powervalue, 9);
    lv_obj_set_align(ui_powervalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powervalue, "7.2");
    lv_obj_set_style_text_font(ui_powervalue, &ui_font_supp21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_power);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 3);
    lv_obj_set_y(ui_Label8, 32);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "KW");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerlabel = lv_label_create(ui_powerandenergy);
    lv_obj_set_width(ui_powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerlabel, 93);
    lv_obj_set_y(ui_powerlabel, -52);
    lv_obj_set_align(ui_powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerlabel, "POWER");
    lv_obj_set_style_text_color(ui_powerlabel, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_powerandenergy);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 310);
    lv_obj_set_height(ui_Bar3, 5);
    lv_obj_set_x(ui_Bar3, 0);
    lv_obj_set_y(ui_Bar3, 92);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Bar3, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_duration(ui_Bar3, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x3FC5D9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Bar3, lv_color_hex(0x0BC12F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar3,
                                                                                           lv_obj_get_style_pad_right(ui_Bar3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_soc = lv_label_create(ui_powerandenergy);
    lv_obj_set_width(ui_soc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soc, -103);
    lv_obj_set_y(ui_soc, 82);
    lv_obj_set_align(ui_soc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soc, "SOC || 46%  || 01:21:50");
    lv_obj_set_style_text_color(ui_soc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soc, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopcharging = lv_label_create(ui_powerandenergy);
    lv_obj_set_width(ui_stopcharging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stopcharging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stopcharging, 104);
    lv_obj_set_y(ui_stopcharging, 83);
    lv_obj_set_align(ui_stopcharging, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stopcharging, "Tap card to stop");
    lv_obj_set_style_text_color(ui_stopcharging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stopcharging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stopcharging, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_powerandenergy, ui_event_powerandenergy, LV_EVENT_ALL, NULL);

}

void ui_powerandenergy_screen_destroy(void)
{
    if(ui_powerandenergy) lv_obj_del(ui_powerandenergy);

    // NULL screen variables
    ui_powerandenergy = NULL;
    ui_header5 = NULL;
    ui_logo3 = NULL;
    ui_momentum3 = NULL;
    ui_status3 = NULL;
    ui_wifi3 = NULL;
    ui_Image9 = NULL;
    ui_footer5 = NULL;
    ui_sync5 = NULL;
    ui_systemReady5 = NULL;
    ui_Image11 = NULL;
    ui_energy = NULL;
    ui_energydeliver = NULL;
    ui_energyvalue = NULL;
    ui_kwh = NULL;
    ui_power = NULL;
    ui_Arc1 = NULL;
    ui_powervalue = NULL;
    ui_Label8 = NULL;
    ui_powerlabel = NULL;
    ui_Bar3 = NULL;
    ui_soc = NULL;
    ui_stopcharging = NULL;

}
