// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_POWERANDENERGY_H
#define UI_POWERANDENERGY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_powerandenergy
extern void ui_powerandenergy_screen_init(void);
extern void ui_powerandenergy_screen_destroy(void);
extern void ui_event_powerandenergy(lv_event_t * e);
extern lv_obj_t * ui_powerandenergy;
extern lv_obj_t * ui_header5;
extern lv_obj_t * ui_logo3;
extern lv_obj_t * ui_momentum3;
extern lv_obj_t * ui_status3;
extern lv_obj_t * ui_wifi3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_footer5;
extern lv_obj_t * ui_sync5;
extern lv_obj_t * ui_systemReady5;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_energy;
extern lv_obj_t * ui_energydeliver;
extern lv_obj_t * ui_energyvalue;
extern lv_obj_t * ui_kwh;
extern lv_obj_t * ui_power;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_powervalue;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_powerlabel;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_soc;
extern lv_obj_t * ui_stopcharging;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

