// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * uic_wifi;
lv_obj_t * ui_ready2charge = NULL;
lv_obj_t * ui_mid2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_flashready2charge = NULL;
lv_obj_t * ui_authenticate1 = NULL;
lv_obj_t * ui_verify1 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_handshake1 = NULL;
lv_obj_t * ui_timeout1 = NULL;
lv_obj_t * ui_ccs = NULL;
lv_obj_t * ui_renewable = NULL;
lv_obj_t * ui_leave = NULL;
lv_obj_t * ui_ccs2 = NULL;
lv_obj_t * ui_time1 = NULL;
lv_obj_t * ui_header2 = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_momentum = NULL;
lv_obj_t * ui_status = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_footer2 = NULL;
lv_obj_t * ui_sync2 = NULL;
lv_obj_t * ui_systemReady2 = NULL;
lv_obj_t * ui_secure = NULL;
// event funtions
void ui_event_ready2charge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_vehicleconnectedscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500,
                          &ui_vehicleconnectedscreen_screen_init);
    }
}

void ui_event_mid2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        blink_Animation(ui_Container2, 50);
    }
}

void ui_event_flashready2charge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        blink_Animation(ui_flashready2charge, 50);
    }
}

void ui_event_Bar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_bar_increment(ui_Bar2, 1, LV_ANIM_ON);
    }
}

// build funtions

void ui_ready2charge_screen_init(void)
{
    ui_ready2charge = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ready2charge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mid2 = lv_obj_create(ui_ready2charge);
    lv_obj_remove_style_all(ui_mid2);
    lv_obj_set_width(ui_mid2, 305);
    lv_obj_set_height(ui_mid2, 166);
    lv_obj_set_x(ui_mid2, 0);
    lv_obj_set_y(ui_mid2, 6);
    lv_obj_set_align(ui_mid2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mid2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mid2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mid2, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mid2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mid2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mid2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_mid2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_mid2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_mid2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 61);
    lv_obj_set_height(ui_Container2, 61);
    lv_obj_set_x(ui_Container2, 2);
    lv_obj_set_y(ui_Container2, -5);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flashready2charge = lv_image_create(ui_Container2);
    lv_image_set_src(ui_flashready2charge, &ui_img_971831803);
    lv_obj_set_width(ui_flashready2charge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flashready2charge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_flashready2charge, 0);
    lv_obj_set_y(ui_flashready2charge, 2);
    lv_obj_set_align(ui_flashready2charge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flashready2charge, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_flashready2charge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_authenticate1 = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_authenticate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_authenticate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_authenticate1, 4);
    lv_obj_set_y(ui_authenticate1, 40);
    lv_obj_set_align(ui_authenticate1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_authenticate1, "READY TO CHARGE");
    lv_obj_set_style_text_color(ui_authenticate1, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_authenticate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_authenticate1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_verify1 = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_verify1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_verify1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_verify1, -1);
    lv_obj_set_y(ui_verify1, 54);
    lv_obj_set_align(ui_verify1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_verify1, "Starting session");
    lv_obj_set_style_text_color(ui_verify1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_verify1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_verify1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_mid2);
    lv_bar_set_value(ui_Bar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 296);
    lv_obj_set_height(ui_Bar2, 4);
    lv_obj_set_x(ui_Bar2, 0);
    lv_obj_set_y(ui_Bar2, 80);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x20555C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar2,
                                                                                           lv_obj_get_style_pad_right(ui_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_handshake1 = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_handshake1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_handshake1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_handshake1, -111);
    lv_obj_set_y(ui_handshake1, 68);
    lv_obj_set_align(ui_handshake1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_handshake1, "HANDSHAKE");
    lv_obj_set_style_text_color(ui_handshake1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_handshake1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_handshake1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeout1 = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_timeout1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeout1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeout1, 91);
    lv_obj_set_y(ui_timeout1, 69);
    lv_obj_set_align(ui_timeout1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeout1, "Timeout in");
    lv_obj_set_style_text_color(ui_timeout1, lv_color_hex(0x14E0D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeout1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeout1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ccs = lv_image_create(ui_mid2);
    lv_image_set_src(ui_ccs, &ui_img_1109516387);
    lv_obj_set_width(ui_ccs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ccs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ccs, -129);
    lv_obj_set_y(ui_ccs, -69);
    lv_obj_set_align(ui_ccs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ccs, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ccs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ccs, 130);

    ui_renewable = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_renewable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_renewable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_renewable, -59);
    lv_obj_set_y(ui_renewable, -71);
    lv_obj_set_align(ui_renewable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_renewable, "100% RENEWABLE");
    lv_obj_set_style_text_color(ui_renewable, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_renewable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_renewable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leave = lv_image_create(ui_mid2);
    lv_image_set_src(ui_leave, &ui_img_1451869231);
    lv_obj_set_width(ui_leave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leave, 89);
    lv_obj_set_y(ui_leave, -71);
    lv_obj_set_align(ui_leave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leave, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_leave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_leave, 100);

    ui_ccs2 = lv_label_create(ui_mid2);
    lv_obj_set_width(ui_ccs2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ccs2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ccs2, 118);
    lv_obj_set_y(ui_ccs2, -72);
    lv_obj_set_align(ui_ccs2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ccs2, "CCS2");
    lv_obj_set_style_text_color(ui_ccs2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ccs2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ccs2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1 = lv_label_create(ui_ready2charge);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1, 132);
    lv_obj_set_y(ui_time1, 75);
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "06s");
    lv_obj_set_style_text_color(ui_time1, lv_color_hex(0x40B6AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = lv_obj_create(ui_ready2charge);
    lv_obj_remove_style_all(ui_header2);
    lv_obj_set_width(ui_header2, 323);
    lv_obj_set_height(ui_header2, 27);
    lv_obj_set_x(ui_header2, -1);
    lv_obj_set_y(ui_header2, -103);
    lv_obj_set_align(ui_header2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header2, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_image_create(ui_header2);
    lv_image_set_src(ui_logo, &ui_img_1149014773);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, -138);
    lv_obj_set_y(ui_logo, -2);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo, 80);

    ui_momentum = lv_label_create(ui_header2);
    lv_obj_set_width(ui_momentum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum, -82);
    lv_obj_set_y(ui_momentum, -2);
    lv_obj_set_align(ui_momentum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum, "MOMENTUM");
    lv_obj_set_style_text_color(ui_momentum, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_header2);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, 96);
    lv_obj_set_y(ui_status, -3);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "READY");
    lv_obj_set_style_text_color(ui_status, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_image_create(ui_header2);
    lv_image_set_src(ui_wifi, &ui_img_493105991);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi, 135);
    lv_obj_set_y(ui_wifi, -3);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi, 120);

    ui_footer2 = lv_obj_create(ui_ready2charge);
    lv_obj_remove_style_all(ui_footer2);
    lv_obj_set_width(ui_footer2, 313);
    lv_obj_set_height(ui_footer2, 17);
    lv_obj_set_x(ui_footer2, -1);
    lv_obj_set_y(ui_footer2, 107);
    lv_obj_set_align(ui_footer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer2, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync2 = lv_label_create(ui_footer2);
    lv_obj_set_width(ui_sync2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync2, 117);
    lv_obj_set_y(ui_sync2, 0);
    lv_obj_set_align(ui_sync2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync2, "SECURED");
    lv_obj_set_style_text_color(ui_sync2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady2 = lv_label_create(ui_footer2);
    lv_obj_set_width(ui_systemReady2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady2, -113);
    lv_obj_set_y(ui_systemReady2, -1);
    lv_obj_set_align(ui_systemReady2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady2, "SYSTEM READY");
    lv_obj_set_style_text_color(ui_systemReady2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secure = lv_image_create(ui_footer2);
    lv_image_set_src(ui_secure, &ui_img_1009779686);
    lv_obj_set_width(ui_secure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secure, 79);
    lv_obj_set_y(ui_secure, 0);
    lv_obj_set_align(ui_secure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secure, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_secure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_secure, 80);

    lv_obj_add_event_cb(ui_flashready2charge, ui_event_flashready2charge, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bar2, ui_event_Bar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mid2, ui_event_mid2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ready2charge, ui_event_ready2charge, LV_EVENT_ALL, NULL);
    uic_wifi = ui_wifi;

}

void ui_ready2charge_screen_destroy(void)
{
    if(ui_ready2charge) lv_obj_del(ui_ready2charge);

    // NULL screen variables
    ui_ready2charge = NULL;
    ui_mid2 = NULL;
    ui_Container2 = NULL;
    ui_flashready2charge = NULL;
    ui_authenticate1 = NULL;
    ui_verify1 = NULL;
    ui_Bar2 = NULL;
    ui_handshake1 = NULL;
    ui_timeout1 = NULL;
    ui_ccs = NULL;
    ui_renewable = NULL;
    ui_leave = NULL;
    ui_ccs2 = NULL;
    ui_time1 = NULL;
    ui_header2 = NULL;
    ui_logo = NULL;
    ui_momentum = NULL;
    ui_status = NULL;
    uic_wifi = NULL;
    ui_wifi = NULL;
    ui_footer2 = NULL;
    ui_sync2 = NULL;
    ui_systemReady2 = NULL;
    ui_secure = NULL;

}
