// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * uic_systemReady;
lv_obj_t * uic_footer;
lv_obj_t * uic_header;
lv_obj_t * uic_tapcard;
lv_obj_t * uic_readytext;
lv_obj_t * uic_chargingstation;
lv_obj_t * uic_Ready;
lv_obj_t * ui_Ready = NULL;
lv_obj_t * ui_mid = NULL;
lv_obj_t * ui_chargingstation = NULL;
lv_obj_t * ui_readytext = NULL;
lv_obj_t * ui_tapcard = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_footer = NULL;
lv_obj_t * ui_sync = NULL;
lv_obj_t * ui_systemReady = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Ready(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_connection, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_connection_screen_init);
    }
}

void ui_event_mid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        blink_Animation(ui_Container4, 50);
    }
}

// build funtions

void ui_Ready_screen_init(void)
{
    ui_Ready = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Ready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mid = lv_obj_create(ui_Ready);
    lv_obj_remove_style_all(ui_mid);
    lv_obj_set_width(ui_mid, 305);
    lv_obj_set_height(ui_mid, 166);
    lv_obj_set_x(ui_mid, 0);
    lv_obj_set_y(ui_mid, 6);
    lv_obj_set_align(ui_mid, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mid, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mid, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_mid, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_mid, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chargingstation = lv_image_create(ui_mid);
    lv_image_set_src(ui_chargingstation, &ui_img_1149014773);
    lv_obj_set_width(ui_chargingstation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chargingstation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chargingstation, 0);
    lv_obj_set_y(ui_chargingstation, -25);
    lv_obj_set_align(ui_chargingstation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chargingstation, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_chargingstation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_readytext = lv_label_create(ui_mid);
    lv_obj_set_width(ui_readytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_readytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_readytext, 4);
    lv_obj_set_y(ui_readytext, 24);
    lv_obj_set_align(ui_readytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_readytext, "READY");
    lv_obj_set_style_text_font(ui_readytext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tapcard = lv_label_create(ui_mid);
    lv_obj_set_width(ui_tapcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tapcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tapcard, 6);
    lv_obj_set_y(ui_tapcard, 48);
    lv_obj_set_align(ui_tapcard, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tapcard, "TAP CARD TO BEGIN");
    lv_obj_set_style_text_color(ui_tapcard, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tapcard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tapcard, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_mid);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 140);
    lv_obj_set_height(ui_Container4, 120);
    lv_obj_set_x(ui_Container4, 7);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_Ready);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_width(ui_header, 323);
    lv_obj_set_height(ui_header, 27);
    lv_obj_set_x(ui_header, -1);
    lv_obj_set_y(ui_header, -103);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_header);
    lv_image_set_src(ui_Image2, &ui_img_733590283);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -138);
    lv_obj_set_y(ui_Image2, -2);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 120);

    ui_Label5 = lv_label_create(ui_header);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -82);
    lv_obj_set_y(ui_Label5, -2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MOMENTUM");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_header);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 91);
    lv_obj_set_y(ui_Label6, -2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "ONLINE");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_header);
    lv_image_set_src(ui_Image3, &ui_img_493105991);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 135);
    lv_obj_set_y(ui_Image3, -3);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 120);

    ui_footer = lv_obj_create(ui_Ready);
    lv_obj_remove_style_all(ui_footer);
    lv_obj_set_width(ui_footer, 313);
    lv_obj_set_height(ui_footer, 17);
    lv_obj_set_x(ui_footer, -1);
    lv_obj_set_y(ui_footer, 107);
    lv_obj_set_align(ui_footer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync = lv_label_create(ui_footer);
    lv_obj_set_width(ui_sync, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync, 117);
    lv_obj_set_y(ui_sync, 0);
    lv_obj_set_align(ui_sync, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync, "SYNC ACTIVE");
    lv_obj_set_style_text_color(ui_sync, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady = lv_label_create(ui_footer);
    lv_obj_set_width(ui_systemReady, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady, -110);
    lv_obj_set_y(ui_systemReady, 0);
    lv_obj_set_align(ui_systemReady, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady, "SYSTEM READY");
    lv_obj_set_style_text_color(ui_systemReady, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Ready);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1232);
    lv_obj_set_y(ui_Label3, 81);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "text");

    lv_obj_add_event_cb(ui_mid, ui_event_mid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ready, ui_event_Ready, LV_EVENT_ALL, NULL);
    uic_Ready = ui_Ready;
    uic_chargingstation = ui_chargingstation;
    uic_readytext = ui_readytext;
    uic_tapcard = ui_tapcard;
    uic_header = ui_header;
    uic_footer = ui_footer;
    uic_systemReady = ui_systemReady;

}

void ui_Ready_screen_destroy(void)
{
    if(ui_Ready) lv_obj_del(ui_Ready);

    // NULL screen variables
    uic_Ready = NULL;
    ui_Ready = NULL;
    ui_mid = NULL;
    uic_chargingstation = NULL;
    ui_chargingstation = NULL;
    uic_readytext = NULL;
    ui_readytext = NULL;
    uic_tapcard = NULL;
    ui_tapcard = NULL;
    ui_Container4 = NULL;
    uic_header = NULL;
    ui_header = NULL;
    ui_Image2 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Image3 = NULL;
    uic_footer = NULL;
    ui_footer = NULL;
    ui_sync = NULL;
    uic_systemReady = NULL;
    ui_systemReady = NULL;
    ui_Label3 = NULL;

}
