// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_READY2CHARGE_H
#define UI_READY2CHARGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ready2charge
extern void ui_ready2charge_screen_init(void);
extern void ui_ready2charge_screen_destroy(void);
extern void ui_event_ready2charge(lv_event_t * e);
extern lv_obj_t * ui_ready2charge;
extern void ui_event_mid2(lv_event_t * e);
extern lv_obj_t * ui_mid2;
extern lv_obj_t * ui_Container2;
extern void ui_event_flashready2charge(lv_event_t * e);
extern lv_obj_t * ui_flashready2charge;
extern lv_obj_t * ui_authenticate1;
extern lv_obj_t * ui_verify1;
extern void ui_event_Bar2(lv_event_t * e);
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_handshake1;
extern lv_obj_t * ui_timeout1;
extern lv_obj_t * ui_ccs;
extern lv_obj_t * ui_renewable;
extern lv_obj_t * ui_leave;
extern lv_obj_t * ui_ccs2;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_header2;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_momentum;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_footer2;
extern lv_obj_t * ui_sync2;
extern lv_obj_t * ui_systemReady2;
extern lv_obj_t * ui_secure;
// CUSTOM VARIABLES
extern lv_obj_t * uic_wifi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

