// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_READY_H
#define UI_READY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Ready
extern void ui_Ready_screen_init(void);
extern void ui_Ready_screen_destroy(void);
extern void ui_event_Ready(lv_event_t * e);
extern lv_obj_t * ui_Ready;
extern void ui_event_mid(lv_event_t * e);
extern lv_obj_t * ui_mid;
extern lv_obj_t * ui_chargingstation;
extern lv_obj_t * ui_readytext;
extern lv_obj_t * ui_tapcard;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_footer;
extern lv_obj_t * ui_sync;
extern lv_obj_t * ui_systemReady;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Ready;
extern lv_obj_t * uic_chargingstation;
extern lv_obj_t * uic_readytext;
extern lv_obj_t * uic_tapcard;
extern lv_obj_t * uic_header;
extern lv_obj_t * uic_footer;
extern lv_obj_t * uic_systemReady;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

