// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * ui_sessioncomplete = NULL;
lv_obj_t * ui_header6 = NULL;
lv_obj_t * ui_logo4 = NULL;
lv_obj_t * ui_momentum4 = NULL;
lv_obj_t * ui_status4 = NULL;
lv_obj_t * ui_wifi4 = NULL;
lv_obj_t * ui_footer6 = NULL;
lv_obj_t * ui_sync6 = NULL;
lv_obj_t * ui_systemReady6 = NULL;
lv_obj_t * ui_done = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_sessioncompletelabel = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_delivered = NULL;
lv_obj_t * ui_deliveredvalue = NULL;
lv_obj_t * ui_unit = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_retuningtoidle = NULL;
// event funtions
void ui_event_sessioncomplete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_fault, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_fault_screen_init);
    }
}

// build funtions

void ui_sessioncomplete_screen_init(void)
{
    ui_sessioncomplete = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sessioncomplete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header6 = lv_obj_create(ui_sessioncomplete);
    lv_obj_remove_style_all(ui_header6);
    lv_obj_set_width(ui_header6, 323);
    lv_obj_set_height(ui_header6, 27);
    lv_obj_set_x(ui_header6, -1);
    lv_obj_set_y(ui_header6, -103);
    lv_obj_set_align(ui_header6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header6, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo4 = lv_image_create(ui_header6);
    lv_image_set_src(ui_logo4, &ui_img_1149014773);
    lv_obj_set_width(ui_logo4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo4, -138);
    lv_obj_set_y(ui_logo4, -2);
    lv_obj_set_align(ui_logo4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo4, 80);

    ui_momentum4 = lv_label_create(ui_header6);
    lv_obj_set_width(ui_momentum4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum4, -82);
    lv_obj_set_y(ui_momentum4, -2);
    lv_obj_set_align(ui_momentum4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum4, "MOMENTUM");
    lv_obj_set_style_text_color(ui_momentum4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status4 = lv_label_create(ui_header6);
    lv_obj_set_width(ui_status4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status4, 96);
    lv_obj_set_y(ui_status4, -2);
    lv_obj_set_align(ui_status4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status4, "DONE");
    lv_obj_set_style_text_color(ui_status4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_status4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_status4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_status4, lv_color_hex(0x143D43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_status4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_status4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_status4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_status4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_status4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_status4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_status4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_status4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi4 = lv_image_create(ui_header6);
    lv_image_set_src(ui_wifi4, &ui_img_493105991);
    lv_obj_set_width(ui_wifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi4, 135);
    lv_obj_set_y(ui_wifi4, -3);
    lv_obj_set_align(ui_wifi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi4, 120);

    ui_footer6 = lv_obj_create(ui_sessioncomplete);
    lv_obj_remove_style_all(ui_footer6);
    lv_obj_set_width(ui_footer6, 313);
    lv_obj_set_height(ui_footer6, 17);
    lv_obj_set_x(ui_footer6, -1);
    lv_obj_set_y(ui_footer6, 107);
    lv_obj_set_align(ui_footer6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer6, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync6 = lv_label_create(ui_footer6);
    lv_obj_set_width(ui_sync6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync6, 117);
    lv_obj_set_y(ui_sync6, 0);
    lv_obj_set_align(ui_sync6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync6, "System Ready");
    lv_obj_set_style_text_color(ui_sync6, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady6 = lv_label_create(ui_footer6);
    lv_obj_set_width(ui_systemReady6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady6, -107);
    lv_obj_set_y(ui_systemReady6, 1);
    lv_obj_set_align(ui_systemReady6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady6, "Returning to idle..");
    lv_obj_set_style_text_color(ui_systemReady6, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_done = lv_obj_create(ui_sessioncomplete);
    lv_obj_remove_style_all(ui_done);
    lv_obj_set_width(ui_done, 58);
    lv_obj_set_height(ui_done, 56);
    lv_obj_set_x(ui_done, 1);
    lv_obj_set_y(ui_done, -49);
    lv_obj_set_align(ui_done, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_done, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_done, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_done, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_done, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_done, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_done, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_done);
    lv_image_set_src(ui_Image12, &ui_img_633336028);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_sessioncomplete);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 290);
    lv_obj_set_height(ui_Container7, 89);
    lv_obj_set_x(ui_Container7, -1);
    lv_obj_set_y(ui_Container7, 33);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container7, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sessioncompletelabel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sessioncompletelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sessioncompletelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sessioncompletelabel, 7);
    lv_obj_set_y(ui_sessioncompletelabel, -25);
    lv_obj_set_align(ui_sessioncompletelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sessioncompletelabel, "SESSION COMPLETE");
    lv_obj_set_style_text_font(ui_sessioncompletelabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 115);
    lv_obj_set_height(ui_Container8, 37);
    lv_obj_set_x(ui_Container8, -79);
    lv_obj_set_y(ui_Container8, 15);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container8, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container8, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delivered = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_delivered, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delivered, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_delivered, -13);
    lv_obj_set_y(ui_delivered, -9);
    lv_obj_set_align(ui_delivered, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delivered, "DELIVERED");
    lv_obj_set_style_text_color(ui_delivered, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_delivered, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_delivered, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deliveredvalue = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_deliveredvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deliveredvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deliveredvalue, -32);
    lv_obj_set_y(ui_deliveredvalue, 7);
    lv_obj_set_align(ui_deliveredvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deliveredvalue, "18.42");
    lv_obj_set_style_text_font(ui_deliveredvalue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unit = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unit, -2);
    lv_obj_set_y(ui_unit, 8);
    lv_obj_set_align(ui_unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unit, "kwh");
    lv_obj_set_style_text_color(ui_unit, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 115);
    lv_obj_set_height(ui_Container9, 37);
    lv_obj_set_x(ui_Container9, 73);
    lv_obj_set_y(ui_Container9, 15);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container9, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -34);
    lv_obj_set_y(ui_Label9, -10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "COST");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_sessioncomplete);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 27);
    lv_obj_set_y(ui_Label10, 55);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "$");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_sessioncomplete);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 48);
    lv_obj_set_y(ui_Label11, 55);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "2.95");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_retuningtoidle = lv_bar_create(ui_sessioncomplete);
    lv_bar_set_value(ui_retuningtoidle, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_retuningtoidle, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_retuningtoidle, 312);
    lv_obj_set_height(ui_retuningtoidle, 2);
    lv_obj_set_x(ui_retuningtoidle, 0);
    lv_obj_set_y(ui_retuningtoidle, 95);
    lv_obj_set_align(ui_retuningtoidle, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_retuningtoidle, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_retuningtoidle,
                                                                                                     lv_obj_get_style_pad_right(ui_retuningtoidle, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_sessioncomplete, ui_event_sessioncomplete, LV_EVENT_ALL, NULL);

}

void ui_sessioncomplete_screen_destroy(void)
{
    if(ui_sessioncomplete) lv_obj_del(ui_sessioncomplete);

    // NULL screen variables
    ui_sessioncomplete = NULL;
    ui_header6 = NULL;
    ui_logo4 = NULL;
    ui_momentum4 = NULL;
    ui_status4 = NULL;
    ui_wifi4 = NULL;
    ui_footer6 = NULL;
    ui_sync6 = NULL;
    ui_systemReady6 = NULL;
    ui_done = NULL;
    ui_Image12 = NULL;
    ui_Container7 = NULL;
    ui_sessioncompletelabel = NULL;
    ui_Container8 = NULL;
    ui_delivered = NULL;
    ui_deliveredvalue = NULL;
    ui_unit = NULL;
    ui_Container9 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_retuningtoidle = NULL;

}
