// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_STOPPEDSREEN_H
#define UI_STOPPEDSREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_stoppedsreen
extern void ui_stoppedsreen_screen_init(void);
extern void ui_stoppedsreen_screen_destroy(void);
extern lv_obj_t * ui_stoppedsreen;
extern lv_obj_t * ui_header7;
extern lv_obj_t * ui_logo5;
extern lv_obj_t * ui_momentum5;
extern lv_obj_t * ui_wifi5;
extern lv_obj_t * ui_footer7;
extern lv_obj_t * ui_sync7;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label13;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

