// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_SESSIONCOMPLETE_H
#define UI_SESSIONCOMPLETE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sessioncomplete
extern void ui_sessioncomplete_screen_init(void);
extern void ui_sessioncomplete_screen_destroy(void);
extern void ui_event_sessioncomplete(lv_event_t * e);
extern lv_obj_t * ui_sessioncomplete;
extern lv_obj_t * ui_header6;
extern lv_obj_t * ui_logo4;
extern lv_obj_t * ui_momentum4;
extern lv_obj_t * ui_status4;
extern lv_obj_t * ui_wifi4;
extern lv_obj_t * ui_footer6;
extern lv_obj_t * ui_sync6;
extern lv_obj_t * ui_systemReady6;
extern lv_obj_t * ui_done;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_sessioncompletelabel;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_delivered;
extern lv_obj_t * ui_deliveredvalue;
extern lv_obj_t * ui_unit;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_retuningtoidle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

