// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * ui_stoppedsreen = NULL;
lv_obj_t * ui_header7 = NULL;
lv_obj_t * ui_logo5 = NULL;
lv_obj_t * ui_momentum5 = NULL;
lv_obj_t * ui_wifi5 = NULL;
lv_obj_t * ui_footer7 = NULL;
lv_obj_t * ui_sync7 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Ready, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_Ready_screen_init);
    }
}

// build funtions

void ui_stoppedsreen_screen_init(void)
{
    ui_stoppedsreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_stoppedsreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header7 = lv_obj_create(ui_stoppedsreen);
    lv_obj_remove_style_all(ui_header7);
    lv_obj_set_width(ui_header7, 323);
    lv_obj_set_height(ui_header7, 27);
    lv_obj_set_x(ui_header7, -1);
    lv_obj_set_y(ui_header7, -103);
    lv_obj_set_align(ui_header7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header7, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo5 = lv_image_create(ui_header7);
    lv_image_set_src(ui_logo5, &ui_img_111783535);
    lv_obj_set_width(ui_logo5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo5, -138);
    lv_obj_set_y(ui_logo5, -2);
    lv_obj_set_align(ui_logo5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo5, 80);

    ui_momentum5 = lv_label_create(ui_header7);
    lv_obj_set_width(ui_momentum5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum5, -94);
    lv_obj_set_y(ui_momentum5, -2);
    lv_obj_set_align(ui_momentum5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum5, "Stopped");
    lv_obj_set_style_text_color(ui_momentum5, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi5 = lv_image_create(ui_header7);
    lv_image_set_src(ui_wifi5, &ui_img_581936926);
    lv_obj_set_width(ui_wifi5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi5, 133);
    lv_obj_set_y(ui_wifi5, -2);
    lv_obj_set_align(ui_wifi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi5, 120);

    ui_footer7 = lv_obj_create(ui_stoppedsreen);
    lv_obj_remove_style_all(ui_footer7);
    lv_obj_set_width(ui_footer7, 313);
    lv_obj_set_height(ui_footer7, 17);
    lv_obj_set_x(ui_footer7, -1);
    lv_obj_set_y(ui_footer7, 107);
    lv_obj_set_align(ui_footer7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer7, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync7 = lv_label_create(ui_footer7);
    lv_obj_set_width(ui_sync7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync7, 79);
    lv_obj_set_y(ui_sync7, 1);
    lv_obj_set_align(ui_sync7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync7, "HARDWARE DISCONNECTED");
    lv_obj_set_style_text_color(ui_sync7, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_stoppedsreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 128);
    lv_obj_set_height(ui_Container11, 100);
    lv_obj_set_x(ui_Container11, 3);
    lv_obj_set_y(ui_Container11, -23);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container11, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_stoppedsreen);
    lv_image_set_src(ui_Image14, &ui_img_1669148290);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, 3);
    lv_obj_set_y(ui_Image14, -24);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_stoppedsreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -1);
    lv_obj_set_y(ui_Label13, 49);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "EMERGENCY STOP ACTIVE");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_stoppedsreen);
    lv_obj_set_width(ui_Button2, 128);
    lv_obj_set_height(ui_Button2, 25);
    lv_obj_set_x(ui_Button2, 7);
    lv_obj_set_y(ui_Button2, 78);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0xF51608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_stoppedsreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 5);
    lv_obj_set_y(ui_Label14, 78);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "RESET");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_stoppedsreen_screen_destroy(void)
{
    if(ui_stoppedsreen) lv_obj_del(ui_stoppedsreen);

    // NULL screen variables
    ui_stoppedsreen = NULL;
    ui_header7 = NULL;
    ui_logo5 = NULL;
    ui_momentum5 = NULL;
    ui_wifi5 = NULL;
    ui_footer7 = NULL;
    ui_sync7 = NULL;
    ui_Container11 = NULL;
    ui_Image14 = NULL;
    ui_Label13 = NULL;
    ui_Button2 = NULL;
    ui_Label14 = NULL;

}
