// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef UI_VEHICLECONNECTEDSCREEN_H
#define UI_VEHICLECONNECTEDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_vehicleconnectedscreen
extern void ui_vehicleconnectedscreen_screen_init(void);
extern void ui_vehicleconnectedscreen_screen_destroy(void);
extern void ui_event_vehicleconnectedscreen(lv_event_t * e);
extern lv_obj_t * ui_vehicleconnectedscreen;
extern lv_obj_t * ui_header4;
extern lv_obj_t * ui_logo2;
extern lv_obj_t * ui_momentum2;
extern lv_obj_t * ui_status2;
extern lv_obj_t * ui_wifi2;
extern lv_obj_t * ui_footer4;
extern lv_obj_t * ui_sync4;
extern lv_obj_t * ui_systemReady4;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_vehicleconneected;
extern lv_obj_t * ui_vehiclereadiness;
extern void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

