// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#include "../ui.h"

lv_obj_t * ui_vehicleconnectedscreen = NULL;
lv_obj_t * ui_header4 = NULL;
lv_obj_t * ui_logo2 = NULL;
lv_obj_t * ui_momentum2 = NULL;
lv_obj_t * ui_status2 = NULL;
lv_obj_t * ui_wifi2 = NULL;
lv_obj_t * ui_footer4 = NULL;
lv_obj_t * ui_sync4 = NULL;
lv_obj_t * ui_systemReady4 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_vehicleconneected = NULL;
lv_obj_t * ui_vehiclereadiness = NULL;
lv_obj_t * ui_Image10 = NULL;
// event funtions
void ui_event_vehicleconnectedscreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_powerandenergy, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_powerandenergy_screen_init);
    }
}

void ui_event_Image10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        blink_Animation(ui_Image10, 500);
    }
}

// build funtions

void ui_vehicleconnectedscreen_screen_init(void)
{
    ui_vehicleconnectedscreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_vehicleconnectedscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header4 = lv_obj_create(ui_vehicleconnectedscreen);
    lv_obj_remove_style_all(ui_header4);
    lv_obj_set_width(ui_header4, 323);
    lv_obj_set_height(ui_header4, 27);
    lv_obj_set_x(ui_header4, -1);
    lv_obj_set_y(ui_header4, -103);
    lv_obj_set_align(ui_header4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header4, lv_color_hex(0x273D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo2 = lv_image_create(ui_header4);
    lv_image_set_src(ui_logo2, &ui_img_1149014773);
    lv_obj_set_width(ui_logo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo2, -138);
    lv_obj_set_y(ui_logo2, -2);
    lv_obj_set_align(ui_logo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_logo2, 80);

    ui_momentum2 = lv_label_create(ui_header4);
    lv_obj_set_width(ui_momentum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_momentum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_momentum2, -82);
    lv_obj_set_y(ui_momentum2, -2);
    lv_obj_set_align(ui_momentum2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_momentum2, "MOMENTUM");
    lv_obj_set_style_text_color(ui_momentum2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_momentum2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_momentum2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status2 = lv_label_create(ui_header4);
    lv_obj_set_width(ui_status2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status2, 96);
    lv_obj_set_y(ui_status2, -3);
    lv_obj_set_align(ui_status2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status2, "READY");
    lv_obj_set_style_text_color(ui_status2, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_status2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi2 = lv_image_create(ui_header4);
    lv_image_set_src(ui_wifi2, &ui_img_493105991);
    lv_obj_set_width(ui_wifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi2, 135);
    lv_obj_set_y(ui_wifi2, -3);
    lv_obj_set_align(ui_wifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifi2, 120);

    ui_footer4 = lv_obj_create(ui_vehicleconnectedscreen);
    lv_obj_remove_style_all(ui_footer4);
    lv_obj_set_width(ui_footer4, 313);
    lv_obj_set_height(ui_footer4, 17);
    lv_obj_set_x(ui_footer4, -1);
    lv_obj_set_y(ui_footer4, 107);
    lv_obj_set_align(ui_footer4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_footer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footer4, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sync4 = lv_label_create(ui_footer4);
    lv_obj_set_width(ui_sync4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sync4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sync4, 117);
    lv_obj_set_y(ui_sync4, 0);
    lv_obj_set_align(ui_sync4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sync4, "CCS TYPE 2");
    lv_obj_set_style_text_color(ui_sync4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sync4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sync4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemReady4 = lv_label_create(ui_footer4);
    lv_obj_set_width(ui_systemReady4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemReady4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemReady4, -113);
    lv_obj_set_y(ui_systemReady4, -1);
    lv_obj_set_align(ui_systemReady4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemReady4, "SYSTEM READY");
    lv_obj_set_style_text_color(ui_systemReady4, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemReady4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemReady4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_vehicleconnectedscreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 70);
    lv_obj_set_x(ui_Container3, -99);
    lv_obj_set_y(ui_Container3, -33);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container3, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_Container3);
    lv_image_set_src(ui_Image8, &ui_img_255880946);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -1);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_vehicleconnectedscreen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 100);
    lv_obj_set_height(ui_Container5, 70);
    lv_obj_set_x(ui_Container5, 92);
    lv_obj_set_y(ui_Container5, -33);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container5, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_Container5);
    lv_image_set_src(ui_Image7, &ui_img_1149014773);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -6);
    lv_obj_set_y(ui_Image7, 1);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_vehicleconnectedscreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 287);
    lv_obj_set_height(ui_Container6, 55);
    lv_obj_set_x(ui_Container6, -1);
    lv_obj_set_y(ui_Container6, 46);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0x1D1D20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container6, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vehicleconneected = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_vehicleconneected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vehicleconneected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vehicleconneected, -2);
    lv_obj_set_y(ui_vehicleconneected, -8);
    lv_obj_set_align(ui_vehicleconneected, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vehicleconneected, "VEHICLE CONNECTED");
    lv_obj_set_style_text_color(ui_vehicleconneected, lv_color_hex(0x3FC5D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vehicleconneected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vehicleconneected, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vehiclereadiness = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_vehiclereadiness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vehiclereadiness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vehiclereadiness, -8);
    lv_obj_set_y(ui_vehiclereadiness, 14);
    lv_obj_set_align(ui_vehiclereadiness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vehiclereadiness, "Waiting for Vehicle readiness");
    lv_obj_set_style_text_color(ui_vehiclereadiness, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vehiclereadiness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vehiclereadiness, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_vehicleconnectedscreen);
    lv_image_set_src(ui_Image10, &ui_img_971831803);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -5);
    lv_obj_set_y(ui_Image10, -32);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image10, ui_event_Image10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vehicleconnectedscreen, ui_event_vehicleconnectedscreen, LV_EVENT_ALL, NULL);

}

void ui_vehicleconnectedscreen_screen_destroy(void)
{
    if(ui_vehicleconnectedscreen) lv_obj_del(ui_vehicleconnectedscreen);

    // NULL screen variables
    ui_vehicleconnectedscreen = NULL;
    ui_header4 = NULL;
    ui_logo2 = NULL;
    ui_momentum2 = NULL;
    ui_status2 = NULL;
    ui_wifi2 = NULL;
    ui_footer4 = NULL;
    ui_sync4 = NULL;
    ui_systemReady4 = NULL;
    ui_Container3 = NULL;
    ui_Image8 = NULL;
    ui_Container5 = NULL;
    ui_Image7 = NULL;
    ui_Container6 = NULL;
    ui_vehicleconneected = NULL;
    ui_vehiclereadiness = NULL;
    ui_Image10 = NULL;

}
