idf_component_register(
    SRCS
        "ui.c"
        "ui_helpers.c"
        "components/ui_comp_temp.c"
        "components/ui_comp.c"
        "components/ui_comp_hook.c"
        "screens/ui_Ready.c"
        "screens/ui_connection.c"
        "screens/ui_ready2charge.c"
        "screens/ui_vehicleconnectedscreen.c"
        "screens/ui_powerandenergy.c"
        "screens/ui_sessioncomplete.c"
        "screens/ui_fault.c"
        "screens/ui_stoppedsreen.c"
        "images/ui_img_1149014773.c"
        "images/ui_img_733590283.c"
        "images/ui_img_493105991.c"
        "images/ui_img_971831803.c"
        "images/ui_img_1109516387.c"
        "images/ui_img_1451869231.c"
        "images/ui_img_1009779686.c"
        "images/ui_img_255880946.c"
        "images/ui_img_98824070.c"
        "images/ui_img_480528337.c"
        "images/ui_img_633336028.c"
        "images/ui_img_1783177842.c"
        "images/ui_img_1554972560.c"
        "images/ui_img_104383894.c"
        "images/ui_img_111783535.c"
        "images/ui_img_581936926.c"
        "images/ui_img_1669148290.c"
        "fonts/ui_font_dis1.c"
        "fonts/ui_font_dis111.c"
        "fonts/ui_font_dis2.c"
        "fonts/ui_font_dis22.c"
        "fonts/ui_font_discipline.c"
        "fonts/ui_font_Font1.c"
        "fonts/ui_font_magicyellow.c"
        "fonts/ui_font_movery.c"
        "fonts/ui_font_psychlone.c"
        "fonts/ui_font_psychlonenotstraight.c"
        "fonts/ui_font_roadstar.c"
        "fonts/ui_font_superpandora.c"
        "fonts/ui_font_supp20.c"
        "fonts/ui_font_supp21.c"
        "fonts/ui_font_supp22.c"
    INCLUDE_DIRS
        "."
        "screens"
        "images"
        "fonts"
        "components"
    REQUIRES lvgl
)