// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: EVSE

#ifndef _EVSE_UI_H
#define _EVSE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Ready.h"
#include "screens/ui_connection.h"
#include "screens/ui_ready2charge.h"
#include "screens/ui_vehicleconnectedscreen.h"
#include "screens/ui_powerandenergy.h"
#include "screens/ui_sessioncomplete.h"
#include "screens/ui_fault.h"
#include "screens/ui_stoppedsreen.h"


///////////////////// VARIABLES ////////////////////

extern lv_anim_t * blink_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1149014773);    // assets/icons8-charging-station-64 (1).png
LV_IMG_DECLARE(ui_img_733590283);    // assets/icons8-circle-48.png
LV_IMG_DECLARE(ui_img_493105991);    // assets/icons8-wi-fi-48.png
LV_IMG_DECLARE(ui_img_971831803);    // assets/icons8-flash-48.png
LV_IMG_DECLARE(ui_img_1109516387);    // assets/icons8-charge-48.png
LV_IMG_DECLARE(ui_img_1451869231);    // assets/icons8-leaves-48.png
LV_IMG_DECLARE(ui_img_1009779686);    // assets/icons8-shield-48.png
LV_IMG_DECLARE(ui_img_255880946);    // assets/icons8-vehicle-50.png
LV_IMG_DECLARE(ui_img_98824070);    // assets/icons8-dot-48.png
LV_IMG_DECLARE(ui_img_480528337);    // assets/icons8-charging-battery-50.png
LV_IMG_DECLARE(ui_img_633336028);    // assets/icons8-done-50.png
LV_IMG_DECLARE(ui_img_1783177842);    // assets/icons8-error-96.png
LV_IMG_DECLARE(ui_img_1554972560);    // assets/icons8-dot-48 (1).png
LV_IMG_DECLARE(ui_img_104383894);    // assets/icons8-general-warning-sign-48.png
LV_IMG_DECLARE(ui_img_111783535);    // assets/icons8-stop-48.png
LV_IMG_DECLARE(ui_img_581936926);    // assets/icons8-offline-48.png
LV_IMG_DECLARE(ui_img_1669148290);    // assets/icons8-stop-hand-96.png

// FONTS
LV_FONT_DECLARE(ui_font_dis1);
LV_FONT_DECLARE(ui_font_dis111);
LV_FONT_DECLARE(ui_font_dis2);
LV_FONT_DECLARE(ui_font_dis22);
LV_FONT_DECLARE(ui_font_discipline);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_magicyellow);
LV_FONT_DECLARE(ui_font_movery);
LV_FONT_DECLARE(ui_font_psychlone);
LV_FONT_DECLARE(ui_font_psychlonenotstraight);
LV_FONT_DECLARE(ui_font_roadstar);
LV_FONT_DECLARE(ui_font_superpandora);
LV_FONT_DECLARE(ui_font_supp20);
LV_FONT_DECLARE(ui_font_supp21);
LV_FONT_DECLARE(ui_font_supp22);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
